---
- name: "Install 'whereamifrom' via Cargo"
  become: false
  community.general.cargo:
    name: whereamifrom
    state: "{{ 'latest' if (whereamifrom_install_version == 'latest') else 'present' }}"
    version: "{{ whereamifrom_install_version }}"
    path: "{{ whereamifrom_install_path }}"
