---
- name: Generate configs
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        path: $HOME/.config/k9s
        state: directory
        recurse: false
        mode: "0750"

    - name: Create k9s views config
      ansible.builtin.copy:
        dest: $HOME/.config/k9s/views.yaml
        content: "{{ k9s_views_overrides | to_nice_yaml(explicit_start=True, indent=2) }}"
        mode: "0644"

- name: Generate shell completions
  block:
    - name: Generate shell completions
      ansible.builtin.command:
        argv:
          - k9s
          - completion
          - "{{ k9s_completions_shell }}"
      register: k9s_completions
      changed_when: k9s_completions.rc != 0

    - name: Write shell completions to file
      become: true
      ansible.builtin.copy:
        dest: /etc/bash_completion.d/k9s
        content: "{{ k9s_completions.stdout }}"
        owner: root
        group: root
        mode: "0644"
