---
- name: Create systemd service
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ item.key }}.service"
    mode: "0644"
  loop: "{{ timers_timers | dict2items }}"

- name: Create systemd timer
  ansible.builtin.template:
    src: timer.j2
    dest: "/etc/systemd/system/{{ item.key }}.timer"
    mode: "0644"
  loop: "{{ timers_timers | dict2items }}"

- name: Make sure service is disabled
  ansible.builtin.systemd_service:
    name: "{{ item.key }}.service"
    enabled: false
  loop: "{{ timers_timers | dict2items }}"

- name: Make sure timer is enabled
  ansible.builtin.systemd_service:
    name: "{{ item.key }}.timer"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ timers_timers | dict2items }}"
