---
- name: Create systemd target
  ansible.builtin.copy:
    src: geesefs.target
    dest: /etc/systemd/system/geesefs.target
    owner: root
    group: root
    mode: '0644'
  notify: "restart geesefs services"

- name: Create systemd target wants directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/geesefs.target.wants
    mode: '0755'

- name: Copy Dismount script
  ansible.builtin.copy:
    src: dismount.py
    dest: /usr/local/bin/dismount.py
    owner: root
    group: root
    mode: '0755'

- name: Create service units
  ansible.builtin.template:
    src: geesefs@.service.j2
    dest: /etc/systemd/system/geesefs@.service
    mode: '0644'
  notify: "restart geesefs services"

- name: Make sure services are started and enabled
  ansible.builtin.systemd_service:
    name: "geesefs@{{ geesefs_bucket_name_prefix }}{{ item }}.service"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ geesefs_buckets }}"

- name: Enable target
  ansible.builtin.systemd_service:
    name: geesefs.target
    enabled: true
